### ISSUE TITLE
Need a list of dependencies to install

### ISSUE THREAD

**Issue by karthanistyr** [DraakBZH/Open-Rolodex#1]
Currently, it is only possible to infer the list of dependencies from the ˋimportˋ list in the source code.

Would it be possible to provide a definitive list of dependencies to install on a system to run the program?

Ideally a list of dependencies obtainable through ˋpipˋ or other package manager.

**Comment by DraakBZH** [comment]
i added them to the readme file and add the requirements.txt file to the project.
Thank you :)
